### PR TITLE
Fix Dead Links

### PR DESCRIPTION
**Pull request by HexF**
This pull request fixes a bunch of dead links between pages found with the new build script. 

There are still a few dead links, mainly ones referencing "Kubernetes Troubleshooting" and many other recipes  which have not been created.

### CODE REVIEW

**Comment by HexF** [comment]
My IDE also went crazy and changed \* to \_ everywhere...

**Comment by Bencey** [comment]
@HexF Can you explain your build script a bit please. Such as what it does, How it is better compared to the current one.

Thanks :)

**Comment by HexF** [comment]
Build script is in #128

**Review by Bencey — CHANGES_REQUESTED** [review]
LGTM, Can we remove the build script and put it in a new PR so that can be further looked at by Funkypenguin

**Comment by HexF** [comment]
@Bencey that should do it

**Review by Bencey — APPROVED** [review]
LGTM

**Review by funkypenguin — APPROVED** [review]
Thanks for cleaning up my messy markdown, @HexF !

**Pull request merged**
