### PR TITLE
Allocated CIDR to ProjectSend

### PR DESCRIPTION
**Pull request by adriankylam**
## Description
Added network allocation to ProjectSend recipe

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have read the [contribution guide](https://geek-cookbook.funkypenguin.co.nz/community/contribute/#contributing-recipes)
- [ ] The format of my changes matches that of other recipes (*ideally it was copied from [template](/manuscript/recipes/template.md)*)
- [ ] My changes have passed markdown linting, either by running `./scripts/local-markdownlint.sh` locally, or by checking the status of the PR check below.

- [ ] I've added at least one footnote to my recipe (*Chef's Notes*)
- [ ] I've updated `common-links.md` in the `_snippets` directory and sorted alphabetically
- [ ] I've updated the navigation in `mkdocs.yaml` in alphabetical order
- [ ] I've updated `CHANGELOG.md` in reverse chronological order order
- [ ] I'm using the [oldest-possible version](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) of Docker-compose syntax for the feature my recipe needs (*v3.2 unless there's a specific need for a later version*)
- [ ] If traefik integration is required, I've included both v1 and v2 labels (*see [template](/manuscript/recipes/template.md)*)
- [ ] If a recipe-specific overlay network is required, I've used a unique subnet and recorded it in [networks.md](manuscript/reference/networks.md)
- [ ] I've considered updating `.github/CODEOWNERS` so that I'll be automatically included as a reviewer on future changes to this recipe

### CODE REVIEW

**Review by funkypenguin — CHANGES_REQUESTED** [review]
Thanks @adriankylam!

Since there's not a recipe published yet for projectsend, this change will create a broken link. Could you remove the link, and just use a "coming soon" placeholder, like you'll see for immich / mastodon?

Thanks!
D

**Comment by adriankylam** [comment]
Looks like the original PR was deleted when I lost access to the repo. I've created a new PR for the ProjectSend recipe.

**Review by funkypenguin — CHANGES_REQUESTED** [review]
Same as before, we don't _have'_ a published (non-premix) ProjectSend recipe yet, so instead of a broken link, how about you replace the link with "ProjectSend (coming soon!)" ?

**Comment by adriankylam** [comment]
Ah oops - sorry I'm so used to the premix that I forgot that non-premix recipes exist. Will update with the link with coming soon as you mentioned.

**Comment by adriankylam** [comment]
Updated

**Review by funkypenguin — APPROVED** [review]
LGTM!

**Pull request merged**
