### PR TITLE
Add note/example for raspberry pi compatability

### PR DESCRIPTION
**Pull request by fumbles**
Added example of using metallb's chart to allow for use of raspberry pi's in cluster. Bitnami's does not have arm64 images.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [contribution guide](https://geek-cookbook.funkypenguin.co.nz/community/contribute/#contributing-recipes)
- [x] The format of my changes matches that of other recipes (*ideally it was copied from [template](/manuscript/recipes/template.md)*)
- [x] My changes have passed markdown linting, either by running `./scripts/local-markdownlint.sh` locally, or by checking the status of the PR check below.

- [ ] I've added at least one footnote to my recipe (*Chef's Notes*)
- [ ] I've updated `common-links.md` in the `_snippets` directory and sorted alphabetically
- [ ] I've updated the navigation in `mkdocs.yaml` in alphabetical order
- [ ] I've updated `CHANGELOG.md` in reverse chronological order order
- [ ] I'm using the [oldest-possible version](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) of Docker-compose syntax for the feature my recipe needs (*v3.2 unless there's a specific need for a later version*)
- [ ] If traefik integration is required, I've included both v1 and v2 labels (*see [template](/manuscript/recipes/template.md)*)
- [ ] If a recipe-specific overlay network is required, I've used a unique subnet and recorded it in [networks.md](manuscript/reference/networks.md)
- [ ] I've considered updating `.github/CODEOWNERS` so that I'll be automatically included as a reviewer on future changes to this recipe

### CODE REVIEW

**Review by fumbles — COMMENTED** [review]
edited to pass lint review

**Review by fumbles — COMMENTED** [review]
More markdown editing for style/compliance

**Review by fumbles — COMMENTED** [review]
Edited style/changed list

**Review by fumbles — COMMENTED** [review]
Cleaned up spaces

**Review by fumbles — COMMENTED** [review]
Sanitizing...

**Review by fumbles — COMMENTED** [review]
Trying to fix README.md:96:52 MD047/single-trailing-newline Files should end with a single newline character

**Review by fumbles — COMMENTED** [review]
Added new line to defeat the markdown linter

**Comment by funkypenguin** [comment]
Thanks @fumbles!

If you look at the [deploy preview](https://deploy-preview-255--geek-cookbook.netlify.app/kubernetes/loadbalancer/metallb/), you'll notice that the markdown didn't quite work:

MetalLB - Kubernetes Bare-Metal Loadbalancing |・∀・ 2023-01-23 12-15-09

May I suggest that you convert your `<detail>` syntax into mkdocs-material's [collapsible admonitions format](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks)?

There are instructions re [using GitPod to preview a PR edit](https://geek-cookbook.funkypenguin.co.nz/community/contribute/#gitpod), which should make it easier to quickly iterate through syntax changes :)

Cheers!
D

**Comment by fumbles** [comment]
Leave to a nitwit or noob (in this area..I work in enterprise storage) to have issues.


Codespaces doesn't really work. It opens up but either my lack of knowledge for vscode or it changed does not show a preview. Can definitely edit though. I see  a standard preview in my local vscode. 

Trying the preview locally `./scripts/serve.sh` yields:
pull access denied for funkypenguin/mkdocs-material, repository does not exist or may require

**Review by fumbles — COMMENTED** [review]
Removed offending newlines

**Review by fumbles — COMMENTED** [review]
Removed the dang indent spaces in the blank line

**Comment by fumbles** [comment]
@funkypenguin  Think we're good finally.  Hopefully it's acceptable.

Unsure about The first check but the lint markdown worked and the mkdocs sanity check is good. I got my local vscode working with mdkocs to view the docs. Works nicely...a ton of plugins to manually install though.

**Comment by funkypenguin** [comment]
Closed because @fumbles solved this in a more elegant way in #257 👍🏻

**Pull request closed without merging**
